name: irctest with Charybdis

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache
          $GITHUB_WORKSPACE/charybdis
        key: ${{ runner.os }}-charybdis

    - name: Install dependencies
      run: |
        sudo apt-get install atheme-services
        python -m pip install --upgrade pip
        pip install pytest -r requirements.txt

    - name: Checkout Charybdis
      uses: actions/checkout@v2
      with:
        repository: charybdis-ircd/charybdis
        ref: charybdis-4.1.2
        path: charybdis

    - name: Build Charybdis
      run: |
        cd $GITHUB_WORKSPACE/charybdis/
        ./autogen.sh
        ./configure --prefix=$HOME/.local/
        make -j 4
        make install

    - name: Test with pytest
      run: |
        # testQuitErrors is very flaky
        # AccountTagTestCase.testInvite fails because https://github.com/solanum-ircd/solanum/issues/166
        PATH=~/.local/bin:$PATH pytest --controller=irctest.controllers.charybdis -k 'not Ergo and not deprecated and not strict and not testDoubleKickMessages and not testQuitErrors and not (AccountTagTestCase and testInvite)'

