name: irctest with Ergo

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - uses: actions/setup-go@v2
      with:
        go-version: '~1.16'
    - run: go version

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache
          $GITHUB_WORKSPACE/ergo
        key: ${{ runner.os }}-ergo

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest -r requirements.txt

    - name: Checkout Ergo
      uses: actions/checkout@v2
      with:
        repository: ergochat/ergo
        ref: irctest_stable
        path: ergo

    - name: Build Ergo
      run: |
        cd $GITHUB_WORKSPACE/ergo/
        make build
        make install

    - name: Test with pytest
      run: |
        PATH=~/go/bin:$PATH make ergo
