name: Lint

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache
        key: ${{ runner.os }}-lint

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pre-commit pytest
        pip install -r requirements.txt

    - name: Lint
      run: |
        pre-commit run -a

    - name: Check generated workflows are in sync
      run: |
        python make_workflows.py
        git diff --exit-code
