name: irctest with Oragono

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache
          $GITHUB_WORKSPACE/oragono
        key: ${{ runner.os }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pre-commit pytest
        pip install -r requirements.txt

    - name: Lint
      run: |
        pre-commit run -a

    - name: Checkout Oragono
      uses: actions/checkout@v2
      with:
        repository: oragono/oragono
        ref: v2.5.1
        path: oragono

    - name: Build Oragono
      run: |
        cd $GITHUB_WORKSPACE/oragono/
        make build
        make install

    - name: Test with pytest
      run: |
        PATH=~/go/bin:$PATH pytest --controller=irctest.controllers.oragono -k 'not deprecated'
