name: irctest with Solanum

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache
          $GITHUB_WORKSPACE/solanum
        key: ${{ runner.os }}-solanum

    - name: Install dependencies
      run: |
        sudo apt-get install atheme-services
        python -m pip install --upgrade pip
        pip install pytest -r requirements.txt

    - name: Checkout Solanum
      uses: actions/checkout@v2
      with:
        repository: solanum-ircd/solanum
        ref: e370888264da666a1bd9faac86cd5f2aa06084f4
        path: solanum

    - name: Build Solanum
      run: |
        cd $GITHUB_WORKSPACE/solanum/
        ./autogen.sh
        ./configure --prefix=$HOME/.local/
        make -j 4
        make install

    - name: Test with pytest
      run: |
        PATH=~/.local/bin:$PATH make solanum



