name: irctest with Sopel

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache
        key: ${{ runner.os }}-sopel

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest sopel==7.0.7 -r requirements.txt

    - name: Test with pytest
      run: |
        PATH=~/.local/bin:$PATH make sopel


